// Generated by view binder compiler. Do not edit!
package com.example.iot_eva2.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.iot_eva2.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnGuardarRegistro;

  @NonNull
  public final EditText etConfirmarClave;

  @NonNull
  public final EditText etCorreo;

  @NonNull
  public final EditText etNuevaClave;

  @NonNull
  public final EditText etNuevoUsuario;

  @NonNull
  public final ImageView imageView4;

  private ActivityRegisterBinding(@NonNull ScrollView rootView, @NonNull Button btnGuardarRegistro,
      @NonNull EditText etConfirmarClave, @NonNull EditText etCorreo,
      @NonNull EditText etNuevaClave, @NonNull EditText etNuevoUsuario,
      @NonNull ImageView imageView4) {
    this.rootView = rootView;
    this.btnGuardarRegistro = btnGuardarRegistro;
    this.etConfirmarClave = etConfirmarClave;
    this.etCorreo = etCorreo;
    this.etNuevaClave = etNuevaClave;
    this.etNuevoUsuario = etNuevoUsuario;
    this.imageView4 = imageView4;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnGuardarRegistro;
      Button btnGuardarRegistro = ViewBindings.findChildViewById(rootView, id);
      if (btnGuardarRegistro == null) {
        break missingId;
      }

      id = R.id.etConfirmarClave;
      EditText etConfirmarClave = ViewBindings.findChildViewById(rootView, id);
      if (etConfirmarClave == null) {
        break missingId;
      }

      id = R.id.etCorreo;
      EditText etCorreo = ViewBindings.findChildViewById(rootView, id);
      if (etCorreo == null) {
        break missingId;
      }

      id = R.id.etNuevaClave;
      EditText etNuevaClave = ViewBindings.findChildViewById(rootView, id);
      if (etNuevaClave == null) {
        break missingId;
      }

      id = R.id.etNuevoUsuario;
      EditText etNuevoUsuario = ViewBindings.findChildViewById(rootView, id);
      if (etNuevoUsuario == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      return new ActivityRegisterBinding((ScrollView) rootView, btnGuardarRegistro,
          etConfirmarClave, etCorreo, etNuevaClave, etNuevoUsuario, imageView4);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
