// Generated by view binder compiler. Do not edit!
package com.example.iot_eva2.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ScrollView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.iot_eva2.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnLogin;

  @NonNull
  public final Button btnRecuperar;

  @NonNull
  public final Button btnRegistrar;

  @NonNull
  public final EditText etClave;

  @NonNull
  public final EditText etUsuario;

  @NonNull
  public final ImageView imageView3;

  private ActivityLoginBinding(@NonNull ScrollView rootView, @NonNull Button btnLogin,
      @NonNull Button btnRecuperar, @NonNull Button btnRegistrar, @NonNull EditText etClave,
      @NonNull EditText etUsuario, @NonNull ImageView imageView3) {
    this.rootView = rootView;
    this.btnLogin = btnLogin;
    this.btnRecuperar = btnRecuperar;
    this.btnRegistrar = btnRegistrar;
    this.etClave = etClave;
    this.etUsuario = etUsuario;
    this.imageView3 = imageView3;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnLogin;
      Button btnLogin = ViewBindings.findChildViewById(rootView, id);
      if (btnLogin == null) {
        break missingId;
      }

      id = R.id.btnRecuperar;
      Button btnRecuperar = ViewBindings.findChildViewById(rootView, id);
      if (btnRecuperar == null) {
        break missingId;
      }

      id = R.id.btnRegistrar;
      Button btnRegistrar = ViewBindings.findChildViewById(rootView, id);
      if (btnRegistrar == null) {
        break missingId;
      }

      id = R.id.etClave;
      EditText etClave = ViewBindings.findChildViewById(rootView, id);
      if (etClave == null) {
        break missingId;
      }

      id = R.id.etUsuario;
      EditText etUsuario = ViewBindings.findChildViewById(rootView, id);
      if (etUsuario == null) {
        break missingId;
      }

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      return new ActivityLoginBinding((ScrollView) rootView, btnLogin, btnRecuperar, btnRegistrar,
          etClave, etUsuario, imageView3);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
